In [1]:
from pyspark.sql import SparkSession
import pyspark.sql.functions as F

spark = (
    SparkSession.builder.appName("pyspark_aula_12")
    .config("spark.sql.repl.eagerEval.enabled", True)
    .getOrCreate()
)

In [ ]:
df = spark.read.parquet("./bases/LOGINS.parquet")

In [3]:
df.groupBy('estado').agg(F.count('*').alias('contagem'))

+------+--------+
|estado|contagem|
+------+--------+
|    SC|      44|
|    RO|      39|
|    PI|      35|
|    AM|      34|
|    RR|      33|
|    GO|      45|
|    TO|      34|
|    MT|      29|
|    SP|      49|
|    ES|      38|
|    PB|      34|
|    RS|      39|
|    MS|      42|
|    AL|      36|
|    MG|      46|
|    PA|      28|
|    BA|      42|
|    SE|      44|
|    PE|      34|
|    CE|      45|
+------+--------+
only showing top 20 rows

In [5]:
livros = spark.read.parquet("./livros.parquet").alias('livros')

compras = spark.read.parquet("./compras.parquet").alias('compras')

In [6]:
df2 = compras.join(livros, compras.cd_livro == livros.id, 'inner')

In [8]:
df2.select('livros.*')

+---------+------------------+---------------+-------------+-------------+--------------+------+
|       id|      cnpj_editora|data_lancamento|          ean|       isbn10|numero_paginas| preco|
+---------+------------------+---------------+-------------+-------------+--------------+------+
|030334762|80.463.719/0001-06|     2013-05-08|7122725133429|0-85193-340-8|           099|123.47|
|013721981|76.351.940/0001-97|     2004-01-27|8786391051693|1-60705-523-6|           379|133.43|
|019458805|81.253.490/0001-30|     2007-12-13|2628486550239|0-916523-25-X|           788|238.54|
|014347542|76.415.890/0001-64|     2007-04-05|3883750237349|0-8360-5203-X|           452|182.43|
|020215846|27.659.813/0001-44|     2014-03-25|7684001180416|0-216-16469-9|           794|155.18|
|010325500|27.689.540/0001-80|     2000-09-09|8793472196570|0-933627-98-X|           306| 30.62|
|053479015|54.327.896/0001-47|     2018-12-21|1750535865566|0-518-04786-5|           105|207.52|
|012331534|84.317.925/0001-50|     2010-05-29|3177832263150|1-62649-755-9|           129|175.67|
|035940339|71.530.496/0001-53|     2014-08-11|6764222732753|1-396-90787-4|           327| 213.6|
|058320651|82.439.107/0001-03|     2013-01-30|6024459409867|1-61357-201-8|           290|196.35|
|032169692|14.603.275/0001-24|     2000-05-15|4659106631807|1-81244-634-9|           956|176.73|
|032169692|14.603.275/0001-24|     2000-05-15|4659106631807|1-81244-634-9|           956|176.73|
|033338998|43.597.816/0001-57|     2015-07-10|5973438592186|0-7598-2346-4|           337|150.51|
|042900595|28.936.451/0001-54|     2010-12-15|2655132597959|0-86582-172-0|           169| 59.35|
|019458805|81.253.490/0001-30|     2007-12-13|2628486550239|0-916523-25-X|           788|238.54|
|027740385|13.695.847/0001-80|     2008-01-05|7379429364080|1-327-99249-3|           991|105.73|
|049141690|95.037.812/0001-18|     2016-12-24|9032214793899|1-4076-9870-2|           454|210.52|
|104361784|46.527.081/0001-83|     2013-12-08|1491898510198|1-101-80944-2|           478|109.14|
|021006591|87.521.043/0001-09|     2019-02-24|1222716689648|1-955093-40-7|           382| 96.84|
|019488257|56.783.210/0001-58|     2013-05-19|3993489629534|0-589-10612-0|           734| 17.11|
+---------+------------------+---------------+-------------+-------------+--------------+------+
only showing top 20 rows